apiVersion: v1
kind: "Service"
metadata:
  name: alertmanager
  namespace: prome
  labels:
    app: alertmanager
spec:
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  selector:
    app: alertmanager
  type: NodePort
