apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: prome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: registry.cn-hangzhou.aliyuncs.com/app_ll/webhook:2024-01-07-23-54-19
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: prome
spec:
  selector:
    app: webhook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

